version: '3.4'
services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image:  redis

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  dsiscount.grpc:
    image: ${DOCKER_REGISTRY-}dsiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Dsiscount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  


